apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: eventing-webhook
  namespace: knative-eventing
  labels:
    app: eventing-webhook
spec:
  podSelector:
    matchLabels:
      app: eventing-webhook
  ingress:
    - {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-webhook-eventing
  namespace: knative-eventing
  labels:
    app: kafka-webhook-eventing
spec:
  podSelector:
    matchLabels:
      app: kafka-webhook-eventing
  ingress:
    - {}
